name: Run

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: v1.x

      - name: compile
        run:  PUPPETEER_PRODUCT=chrome deno compile -A --importmap=import_map.json --unstable https://deno.land/x/puppeteer@16.2.0/install.ts -o hoshino-kaitabi-reservation src/cmd/main.ts
        
      - name: compile2
        run: make build
        
      - name: run
        run: ./out/hoshino-kaitabi-reservation -v
