name: Run

on:
  schedule:
    - cron: '30 6-22 * * *'
  workflow_dispatch:
    inputs:
      sendNotification:
        type: boolean
        required: false
        default: true
        description: 'send notification enabled'

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: /home/runner/.cache/deno
      PUPPETEER_PRODUCT: chrome
      HOSHINO_KAITABI_RESERVATION_SLACK_WEBHOOK_URL: ${{ secrets.HOSHINO_KAITABI_RESERVATION_SLACK_WEBHOOK_URL }}
    outputs:
      sendNotification: ${{ steps.api.outputs.sendNotification }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}-v1
          restore-keys: ${{ runner.os }}-deno-

      - name: install chrome
        run:  deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts

      - name: set slack notification enabled
        if: github.event.inputs.sendNotification
        run: echo "{sendNotification}={--send-notification}" >> $GITHUB_OUTPUT

      - name: run
        run: |
          sendNotification=''
          if [ ${{ github.event.inputs.sendNotification }} ]; then
            sendNotification='--send-notification'
          fi

          deno run -A --importmap=import_map.json src/cmd/main.ts -v -o out/ "$sendNotification"
